version: '3.8'

services:
  app:
    build: .    
    ports: 
      - "3001:3000"
    # volumes:
    #   - .:/app                  # แมปโค้ดทั้งหมดจากโฟลเดอร์โปรเจกต์ในเครื่อง host ไปยังคอนเทนเนอร์
    #   - /app/node_modules       # ใช้ node_modules ภายในคอนเทนเนอร์
    #command: npx next dev
    depends_on:
      - db
      - mysql
    environment:
      - MONGO_URL=mongodb://db:27017/acctax     
      - MYSQL_URL=mysql://tee:tr87AC@mysql:3306/accnewco_acctax
    networks:
      - app-network
  db:
    image: mongo:latest    
    # restart: always
    ports:
      - "27018:27017"
    # volumes:
    #   - mongo-data:/data/db
    networks:
      - app-network

  # mysql:  
  #   image: mysql:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: tee
  #     MYSQL_DATABASE: accnewco_acctax
  #     MYSQL_USER: tee
  #     MYSQL_PASSWORD: tr87AC
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #      - mysql-data:/var/lib/mysql    
  #   networks:
  #     - app-network

volumes:  
  mongo-data:
    driver: local
# mysql-data:

networks:
  app-network:
